# Generated by Django 5.0.2 on 2024-02-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_users_name_alter_users_email_alter_users_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
