runtime: python312

# instance_class: F2

entrypoint: gunicorn -b :$PORT own_trello.wsgi:application



handlers:
- url: /static
  static_dir: static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  APPENGINE_URL: https://own-trello.uc.r.appspot.com/
  DJANGO_SETTINGS_MODULE: own_trello.settings 